### ISSUE TITLE
erroneous eslint errors in stories

### ISSUE THREAD

**Issue by arizzitano** [edx/paragon#151]
Per #150, eslint is throwing some bizarre errors wrt stories. Specifically, it claims Storybook addon functions are imported but not used. Eslint has thrown erroneously in the past and may be related to out-of-sync deps in eslint-config-edx, so this is worth investigating.

**Comment by jaebradley** [comment]
As explained in #162, this is my bad. 

The imported `addDecorator` method is not *actually* getting used (and thus, `eslint` is correct). I'm calling the chained `addDecorator` method.

![alt-text](https://media.giphy.com/media/tEG1nF1v7AL8A/giphy.gif)
