### ISSUE TITLE
Replace CheckBoxGroup and RadioButtonGroup with a FormGroup component

### ISSUE THREAD

**Issue by thallada** [edx/paragon#232]
`CheckBoxGroup` is basically already a `FormGroup` component, so we could make that into one. There is a `RadioButton` component inside of `RadioButtonGroup` that could be pulled out into a separate component. `asInput` could also use the `FormGroup` component, see the [refactor asInput issue](https://github.com/edx/paragon/issues/229).

See [reactstrap's FormGroup](https://reactstrap.github.io/components/form/) for what kind of options it could accept.

**Comment by RichCaloggero** [comment]
Whether you refactor this or not, it seems that these grouping components should allow for a group label and make this a required prop.  A checkbox or radio button group is only useful if it has a group label, and that should be announced by the screen reader as one moves into the group container.

Use either `fieldset` / `legend` or aria (`role="group"). Use either `aria-labelledby` to label the group if the label should be visible, or `aria-label` if it should only be announced to screen readers.

**Comment by abutterworth** [comment]
Implemented in https://github.com/edx/paragon/pull/660, https://github.com/edx/paragon/pull/678, and https://github.com/edx/paragon/pull/682
