### ISSUE TITLE
Should we add Layout components?

### ISSUE THREAD

**Issue by thallada** [edx/paragon#234]
See [reactstrap's Layout components](https://reactstrap.github.io/components/layout/). This would allow us to write:

```jsx
<Container>
  <Row>
    <Col>.col</Col>
  </Row>
</Container>
```

Instead of:

```jsx
<div className="container">
  <div className="row">
    <div className="col">.col</div>
  </div>
</div>
```

**Comment by arizzitano** [comment]
To consider: pull these components in from Reactstrap and re-export them.

**Comment by abutterworth** [comment]
These have been added with React Bootstrap some time ago. Closing this.
