### ISSUE TITLE
Add a Listbox component

### ISSUE THREAD

**Issue by thallada** [edx/paragon#238]
Adding a [listbox](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role) would be useful for selecting items out of a list.

Studio-frontend is currently working on its own implementation of an accessible listbox. Once it is verified to be actually accessible, it could be pulled out into a generic Paragon component.

**Comment by MichaelRoytman** [comment]
This was done in https://github.com/edx/paragon/pull/253.
