### ISSUE TITLE
Switch internal FontAwesome uses to their React inline SVG versions 

### ISSUE THREAD

**Issue by mikix** [edx/paragon#347]
FontAwesome maintains [react-fontawesome](https://www.npmjs.com/package/@fortawesome/react-fontawesome) which provides a FontAwesomeIcon component. This component inlines an svg element which renders the icon (so no webfont at all).

In testing on Prospectus, this saved us having to have new users download all four Pro FA icon files (~430KB) and saved another 12KB (compressed) in FA CSS on the pages.

Not to mention, it means that consumers of Prospectus are no longer tied to FontAwesome 4.0 webfonts.

Everywhere we internally use FA icon class names, we should instead use a FontAwesomeIcon component.

Related tickets:
https://github.com/edx/front-end-cookie-cutter-application/issues/178
https://github.com/edx/frontend-component-footer/issues/21

**Comment by mikix** [comment]
We should also consider dropping (or reworking) Icon? FontAwesomeIcon seems like a replacement.

**Comment by abutterworth** [comment]
With https://github.com/edx/paragon/pull/600 we now have a Paragon solution for icons.
