### ISSUE TITLE
SearchField component: Can't clear the search if the input is empty

### ISSUE THREAD

**Issue by reillz10** [edx/paragon#356]
If a user is to manually clear (backspace out) all of the text in the input field when a search has previously been completed, there is no way to clear the input.

Step 1: Have a search box
![screen shot 2018-10-30 at 1 22 23 pm](https://user-images.githubusercontent.com/11048849/47737414-43052700-dc47-11e8-9e59-36be239db38c.png)

Step 2: Search for something
![screen shot 2018-10-30 at 1 22 35 pm](https://user-images.githubusercontent.com/11048849/47737443-544e3380-dc47-11e8-95e5-730bf2d55ece.png)

Step 3: Clear out the search content and notice that it is impossible to get the full set of data back without typing something into the input
![screen shot 2018-10-30 at 1 22 47 pm](https://user-images.githubusercontent.com/11048849/47737496-7051d500-dc47-11e8-8fb6-e62c2229c3ea.png)

Potential solutions:

1. Maintain the state of whether a search has happened without a clear event and maintain the little x clear button

2. Always allow users to submit a search even if the input is empty

**Comment by adamstankiewicz** [comment]
@reillz10 I've opened a PR to fix this issue: #359

**Comment by adamstankiewicz** [comment]
This issue is resolved in #359. Closing out this issue.
