### ISSUE TITLE
Remove `buttonType` prop from Button component

### ISSUE THREAD

**Issue by adamstankiewicz** [edx/paragon#358]
The `Button` component currently has a `buttonType` prop which allows the consumer to pass in the class name of the Bootstrap button to use (e.g., primary, link, etc.). This value is prefixed with `btn-` and added to the list of class names.

However, we also have a `type` prop which represents the actual type of the button (i.e., submit, reset, button). Having both of these props is confusing as `buttonType` does not actually represent a type of button as it's used as a class name.

Instead, we should deprecate the `buttonType` prop and have consumers of the `Button` component pass in the Bootstrap class name (e.g., `.btn-primary`) in the `className` prop.

_Note: This would be a breaking change._

cc: @georgebabey

**Comment by abutterworth** [comment]
To move forward with removing `buttonType` we can add a new kind of backward compatible deprecation to `withDeprecatedProps`. Maybe a new type like REMOVE or REPLACED or something.
https://github.com/edx/paragon/blob/master/src/withDeprecatedProps.jsx

So usage with exporting Button could be something like:
```
export withDeprecatedProps(Button, {
  buttonType: {
    deprType: DEPR_TYPES.CONSOLIDATED,
    consolidate: (value, transformedProps) => {
      return {
        ...transformedProps,
        className: transformedProps.className + " btn-" + value
    };
  },
});

Do you want to take this on or should I?

**Comment by abutterworth** [comment]
Fixed a while back.
