### ISSUE TITLE
Allow specifying type of InputText

### ISSUE THREAD

**Issue by mikix** [edx/paragon#384]
For an `<input>` element, HTML lets you specify a `type` like `email`, `tel`, or `url`. On some devices (like phones), these each brings up different input interfaces.

I don't see how to set that via InputText props.

**Comment by abutterworth** [comment]
I'd like for us to deprecate asInput and replace it with a passthrough to [Reactstrap's Input component](https://reactstrap.github.io/components/form/) + any shim we need to add to enforce accessibility requirements.

Reactstrap's implementation looks like it will respect those input types. [Reactstrap: Input.jsx: Line 79](https://github.com/reactstrap/reactstrap/blob/master/src/Input.js#L79)

**Comment by wittjeff** [comment]
The accessibility concern comes from a new WCAG 2.1 guideline, 1.3.5
Identify input purpose (AA), which I read to mean ("use HTML5 input types
when possible"). Full details here:
https://alexanderskogberg.com/2018/02/new-guidelines-wcag-2-1-explained/

**Comment by mikix** [comment]
Huh. Apparently InputText does allow type after all. Not sure why I was confused earlier.

Though I will point out that InputText doesn't pass through some type-specific props like step, max, and min. I'll look at that. But will close this ticket.
