### ISSUE TITLE
Support right-aligning a dropdown menu 

### ISSUE THREAD

**Issue by mikix** [edx/paragon#417]
Bootstrap allows setting the dropdown-menu-right on a dropdown-menu.

https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment

It would be nice if a user of paragon could control/set that class. For example, a header menu dropdown that we use on edx.org might be close to the right edge of the screen. That would likely want to be right-aligned.

(Alternatively / additionally, make it so the dropdown menu can't go outside the viewport would be nice. Looks like maybe bootstrap has support for that via a data-boundary option?)

**Comment by abutterworth** [comment]
Good idea. I think Bootstrap achieves this with popper.js
