### ISSUE TITLE
No easy way to control collapsible programmatically

### ISSUE THREAD

**Issue by mikix** [edx/paragon#431]
Looks like it does listen to *changes* in the prop `isOpen`. But if I'm sitting here and want to ensure the collapsible is open, the only sure fire way to do that is to cycle the `isOpen` prop first to `false` and then to `true`.

**Comment by mikix** [comment]
Cycling isOpen to false then true didn't work - presumably I would have needed to give react a cycle of its event loop to handle the switch.

Instead, what worked was keeping track of internal collapsible state by listening to onToggle, and updating the input isOpen prop to match. Then, when I wanted to set to `true`, the Collapsible would notice because I was actually going from false to true.

Something simpler might be nicer? Though maybe you can't get too simple. If you add a method to do it, a consumer would need to grab a reference to the collapsible. But that might be less effort than keeping their own state and adding event handlers.

**Comment by abutterworth** [comment]
You're spot on with this. Many Paragon components keep an internal state for things like "isOpen" and try to merge it with props. In the case of a Collapsible I think it makes sense to have it be able handle it's own open/closed state. But it sounds like we can make a better implementation. If a prop is passed in that should always overrule any internal state. I'll take a look.

**Comment by abutterworth** [comment]
Fixed by https://github.com/edx/paragon/pull/504
