### ISSUE TITLE
Modal should be less opinionated

### ISSUE THREAD

**Issue by abutterworth** [edx/paragon#432]
Generally I think it controls too much:

- the modal can close itself with a button it creates. It should not specify buttons or open/closed state
- the cancel button is created for you, it should not be
- the body content is specified as a prop. It should be specified as children.
- the inner html content is fixed to have a header and footer. Should we remove that and create ModalHeader /> and <ModalFooter /> Components?

**Comment by mikix** [comment]
I agree with this. I'm looking at a design for a modal right now that wants a primary close button on the bottom (rather than secondary), no horizontal lines, centered header text, and a centered close button. All of which need some sort of style overriding to make it work.

**Comment by abutterworth** [comment]
Resolved by https://github.com/edx/paragon/pull/630
