### ISSUE TITLE
Setting renderHeaderCloseButton on a Modal breaks tab navigation

### ISSUE THREAD

**Issue by mikix** [edx/paragon#543]
The Modal component notes the whole modal dialog as its firstFocusableElement when it doesn't have a header close button. And sets `tabindex=-1` on the whole dialog so that paragon can focus it when the modal is opened.

However, when shift-tabbing in the dialog, paragon uses this code:

```
    if (e.key === 'Tab') {
      if (e.shiftKey) {
        if (e.target === this.firstFocusableElement) {
          e.preventDefault();
          this.closeButton.focus();
        }
      } else if (e.target === this.closeButton) {
        e.preventDefault();
        this.firstFocusableElement.focus();
      }
    }
```

Because the dialog is `tabindex=-1`, it won't naturally be included when shift-tabbing and we'll miss that `e.target === this.firstFocusableElement` boundary condition. And just fall right off the modal.

**Comment by abutterworth** [comment]
We have a new Modal implementation in https://github.com/edx/paragon/pull/630. The old Modal is now deprecated.
